name: pyeo_ohne_gdal
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - aws-c-common
  - aws-c-event-stream
  - aws-checksums
  - aws-sdk-cpp
  - babel
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - blosc
  - boto3
  - botocore
  - bottleneck
  - brotli
  - brotlipy
  - brunsli
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charls
  - charset-normalizer
  - cloudpickle
  - colorama
  - comm
  - cryptography
  - curl
  - cycler
  - cytoolz
  - dask-core
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - expat
  - flit-core
  - fontconfig
  - fonttools
  - freetype
  - freexl
  - fsspec
  - geopandas
  - geos
  - geotiff
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - hdf4
  - hdf5
  - icu
  - idna
  - imagecodecs
  - imageio
  - iniconfig
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jmespath
  - joblib
  - jpeg
  - json-c
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - jxrlib
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libaec
  - libboost
  - libcurl
  - libdap4
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgdal
  - libgfortran-ng
  - libgfortran4
  - libgomp
  - libkml
  - libnetcdf
  - libnghttp2
  - libpng
  - libpq
  - libsodium
  - libspatialite
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - libzip
  - libzopfli
  - locket
  - lxml
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - notebook
  - notebook-shim
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - parso
  - partd
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pixman
  - platformdirs
  - pluggy
  - poppler
  - poppler-data
  - proj
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - py
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python-fastjsonschema
  - pytz
  - pywavelets
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - requests
  - s3transfer
  - scikit-image
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - snappy
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - tenacity
  - terminado
  - threadpoolctl
  - tifffile
  - tiledb
  - tinycss2
  - tk
  - toml
  - tomli
  - toolz
  - tornado
  - tqdm
  - traitlets
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xerces-c
  - xz
  - yaml
  - zeromq
  - zfp
  - zlib
  - zstd
  - pip:
      - aenum
      - click
      - click-plugins
      - cligj
      - dataclasses-json
      - fiona
      - geojson
      - geomet
      - html2text
      - marshmallow
      - marshmallow-enum
      - mypy-extensions
      - oauthlib
      - pillow
      - pyproj
      - pysolar
      - pyyaml
      - requests-oauthlib
      - sentinelhub
      - sentinelsat
      - shapely
      - typing-extensions
      - typing-inspect
      - utm
